package compiler

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// TranspileGoxFiles finds .gox files and generates corresponding _gox_gen.go files.
// This is a minimal transpiler that maps simple JSX-like tags to GoFront helper calls.
func TranspileGoxFiles(srcDir string) error {
	return filepath.Walk(srcDir, func(path string, info os.FileInfo, err error) error {
		if err != nil || info == nil || info.IsDir() {
			return err
		}
		if strings.HasSuffix(path, ".gox") {
			genPath := strings.TrimSuffix(path, ".gox") + "_gox_gen.go"
			if err := transpileSingleGox(path, genPath); err != nil {
				return fmt.Errorf("transpile %s: %w", path, err)
			}
		}
		return nil
	})
}

var tagRe = regexp.MustCompile(`(?s)<(/?)([A-Za-z][A-Za-z0-9]*)\s*([^>]*)>|([^<]+)`)
var attrRe = regexp.MustCompile(`([a-zA-Z_:][-a-zA-Z0-9_:.]*)\s*=\s*"([^"]*)"`)

func transpileSingleGox(srcPath, genPath string) error {
	f, err := os.Open(srcPath)
	if err != nil {
		return err
	}
	defer f.Close()
	content, err := io.ReadAll(f)
	if err != nil {
		return err
	}

	// Build component expression from tokens
	tokens := tagRe.FindAllStringSubmatch(string(content), -1)
	var stack []string
	var outBuilder strings.Builder

	// simple helper to emit GoFront expressions for a tag with optional attrs
	emitOpen := func(tag string, attrs string) string {
		tagName := strings.Title(strings.ToLower(tag))
		// supported tags map directly: Div, Span, Button, H1, P, Main, Section, Header, Footer, Text
		var call string
		switch tagName {
		case "Text":
			// Text will be handled as text nodes; do not reach here normally
			call = "GoFront.Text(\"\")"
		default:
			call = fmt.Sprintf("GoFront.%s(", tagName)
		}
		// attributes: id/class
		attrsCalls := []string{}
		if attrs != "" {
			for _, m := range attrRe.FindAllStringSubmatch(attrs, -1) {
				name := strings.ToLower(m[1])
				val := m[2]
				if name == "id" {
					attrsCalls = append(attrsCalls, fmt.Sprintf("GoFront.ID(%q)", val))
				} else if name == "class" {
					attrsCalls = append(attrsCalls, fmt.Sprintf("GoFront.Class(%q)", val))
				}
			}
		}
		if len(attrsCalls) > 0 {
			// we'll close the call and append .With(...) later after children
			return call + ")" + ".With(" + strings.Join(attrsCalls, ", ") + ")"
		}
		return call
	}

	// We'll generate a top-level function based on file name
	base := filepath.Base(srcPath)
	name := strings.TrimSuffix(base, filepath.Ext(base))
	funcName := strings.Title(name)
	// if in components or pages folder, keep conventional suffixes
	// pages/home.gox -> HomePage
	if strings.Contains(srcPath, string(filepath.Separator)+"pages") {
		funcName = strings.Title(name) + "Page"
	}

	outBuilder.WriteString("// Code generated by gofront; DO NOT EDIT.\n")
	outBuilder.WriteString("package ")
	outBuilder.WriteString(detectPackage(srcPath))
	outBuilder.WriteString("\n\nimport GoFront \"github.com/Alazar42/GoFront\"\n\n")
	outBuilder.WriteString(fmt.Sprintf("func %s() GoFront.Component {\n", funcName))
	// We'll produce a single return expression building the tree
	// Use a simple stack of expressions
	var exprStack []string

	for _, tk := range tokens {
		if tk[4] != "" {
			// text node
			txt := strings.TrimSpace(tk[4])
			if txt != "" {
				// escape backticks and quotes
				txt = strings.ReplaceAll(txt, "\n", "\\n")
				exprStack = append(exprStack, fmt.Sprintf("GoFront.Text(%q)", txt))
			}
			continue
		}
		closing := tk[1] == "/"
		tag := tk[2]
		attrs := strings.TrimSpace(tk[3])
		if !closing {
			// open
			tagExpr := emitOpen(tag, attrs)
			// push marker
			exprStack = append(exprStack, tagExpr)
			stack = append(stack, "(")
		} else {
			// close: pop until last open; collect children
			// find last tagExpr index
			var children []string
			for len(exprStack) > 0 {
				last := exprStack[len(exprStack)-1]
				exprStack = exprStack[:len(exprStack)-1]
				if strings.HasPrefix(last, "GoFront.") {
					// treat as an opened tag expression (start)
					// build call: last + children + )
					// children are in reverse order on stack; reverse them
					for i := len(children)/2 - 1; i >= 0; i-- {
						opp := len(children) - 1 - i
						children[i], children[opp] = children[opp], children[i]
					}
					var b strings.Builder
					if strings.HasSuffix(last, ")") && strings.Contains(last, ".With(") {
						// last already closed; it contains .With(...) so it expects children before .With: e.g. GoFront.Div() .With(...)
						// remove trailing ).With... to get base call
						idx := strings.Index(last, ")")
						baseCall := last[:idx+1]
						withPart := last[idx+1:]
						b.WriteString(baseCall)
						if len(children) > 0 {
							b.WriteString(strings.Join(children, ", "))
						}
						b.WriteString(withPart)
					} else {
						// normal: last is e.g. GoFront.Div(
						if strings.HasSuffix(last, "(") {
							b.WriteString(last)
						} else if strings.HasSuffix(last, ")") {
							// unexpected but handle
							b.WriteString(last)
							b.WriteString("(")
						} else {
							b.WriteString(last + "(")
						}
						if len(children) > 0 {
							b.WriteString(strings.Join(children, ", "))
						}
						b.WriteString(")")
					}
					exprStack = append(exprStack, b.String())
					break
				}
				// accumulate as child
				children = append(children, last)
			}
		}
	}

	// final expression
	finalExpr := "GoFront.Div()"
	if len(exprStack) > 0 {
		finalExpr = exprStack[len(exprStack)-1]
	}
	outBuilder.WriteString("\treturn ")
	outBuilder.WriteString(finalExpr)
	outBuilder.WriteString("\n}")

	// write file if changed
	existing, _ := os.ReadFile(genPath)
	if string(existing) != outBuilder.String() {
		if err := os.WriteFile(genPath, []byte(outBuilder.String()), 0o644); err != nil {
			return err
		}
	}
	return nil
}

func detectPackage(path string) string {
	dir := filepath.Dir(path)
	base := filepath.Base(dir)
	if base == "src" || base == "." {
		return "main"
	}
	return base
}
