package compiler

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// TranspileGoxFiles finds .gox files and generates corresponding _gox_gen.go files.
// Supports JSX-like tags with optional <script>, <style>, and <template> blocks (Svelte-like format).
func TranspileGoxFiles(srcDir string) error {
	return filepath.Walk(srcDir, func(path string, info os.FileInfo, err error) error {
		if err != nil || info == nil || info.IsDir() {
			return err
		}
		if strings.HasSuffix(path, ".gox") {
			genPath := generatedGoxPath(srcDir, path)
			if err := transpileSingleGox(path, genPath); err != nil {
				return fmt.Errorf("transpile %s: %w", path, err)
			}
		}
		return nil
	})
}

func generatedGoxPath(srcDir, srcPath string) string {
	rel, err := filepath.Rel(srcDir, srcPath)
	if err != nil {
		base := strings.TrimSuffix(filepath.Base(srcPath), ".gox")
		return filepath.Join(srcDir, ".goxgen", base+"_gox_gen.go")
	}
	flat := strings.TrimSuffix(filepath.ToSlash(rel), ".gox")
	flat = strings.ReplaceAll(flat, "/", "_")
	return filepath.Join(srcDir, ".goxgen", flat+"_gox_gen.go")
}

func legacyGeneratedGoxPath(srcPath string) string {
	return strings.TrimSuffix(srcPath, ".gox") + "_gox_gen.go"
}

var tagRe = regexp.MustCompile(`(?s)<(/?)([A-Za-z][A-Za-z0-9]*)\s*([^>]*)>|([^<]+)`)
var attrRe = regexp.MustCompile(`([a-zA-Z_:][-a-zA-Z0-9_:.]*)\s*=\s*"([^"]*)"`)

type GoxBlocks struct {
	Script   string
	Style    string
	Template string
}

// extractBlocks extracts <script>, <style>, and <template> blocks from .gox content
// Uses string manipulation instead of regex backreferences (not supported in Go regexp)
func extractBlocks(content string) GoxBlocks {
	blocks := GoxBlocks{}

	// Extract <script> block
	scriptStart := strings.Index(content, "<script")
	if scriptStart != -1 {
		scriptTagEnd := strings.Index(content[scriptStart:], ">")
		if scriptTagEnd != -1 {
			searchAfter := scriptStart + scriptTagEnd + 1
			scriptEnd := strings.Index(content[searchAfter:], "</script>")
			if scriptEnd != -1 {
				blocks.Script = strings.TrimSpace(content[searchAfter : searchAfter+scriptEnd])
			}
		}
	}

	// Extract <style> block
	styleStart := strings.Index(content, "<style")
	if styleStart != -1 {
		styleTagEnd := strings.Index(content[styleStart:], ">")
		if styleTagEnd != -1 {
			searchAfter := styleStart + styleTagEnd + 1
			styleEnd := strings.Index(content[searchAfter:], "</style>")
			if styleEnd != -1 {
				blocks.Style = strings.TrimSpace(content[searchAfter : searchAfter+styleEnd])
			}
		}
	}

	// Extract <template> block
	templateStart := strings.Index(content, "<template")
	if templateStart != -1 {
		templateTagEnd := strings.Index(content[templateStart:], ">")
		if templateTagEnd != -1 {
			searchAfter := templateStart + templateTagEnd + 1
			templateEnd := strings.Index(content[searchAfter:], "</template>")
			if templateEnd != -1 {
				blocks.Template = strings.TrimSpace(content[searchAfter : searchAfter+templateEnd])
			}
		}
	}

	// If no <template> block found, use content minus the extracted blocks
	if blocks.Template == "" {
		templateContent := content

		// Remove script block if present
		if scriptStart != -1 {
			scriptTagEnd := strings.Index(content[scriptStart:], ">")
			if scriptTagEnd != -1 {
				searchAfter := scriptStart + scriptTagEnd + 1
				scriptEnd := strings.Index(content[searchAfter:], "</script>")
				if scriptEnd != -1 {
					scriptFullEnd := searchAfter + scriptEnd + len("</script>")
					templateContent = templateContent[:scriptStart] + templateContent[scriptFullEnd:]
				}
			}
		}
		if styleStart != -1 {
			styleTagEnd := strings.Index(content[styleStart:], ">")
			if styleTagEnd != -1 {
				searchAfter := styleStart + styleTagEnd + 1
				styleEnd := strings.Index(content[searchAfter:], "</style>")
				if styleEnd != -1 {
					styleFullEnd := searchAfter + styleEnd + len("</style>")
					templateContent = templateContent[:styleStart] + templateContent[styleFullEnd:]
				}
			}
		}

		blocks.Template = strings.TrimSpace(templateContent)
	}

	return blocks
}

func transpileSingleGox(srcPath, genPath string) error {
	f, err := os.Open(srcPath)
	if err != nil {
		return err
	}
	defer f.Close()
	content, err := io.ReadAll(f)
	if err != nil {
		return err
	}

	blocks := extractBlocks(string(content))

	// Get component name and package
	base := filepath.Base(srcPath)
	name := strings.TrimSuffix(base, filepath.Ext(base))
	funcName := strings.Title(name)
	// if in components or pages folder, keep conventional suffixes
	// pages/home.gox -> HomePage
	if strings.Contains(srcPath, string(filepath.Separator)+"pages") {
		funcName = strings.Title(name) + "Page"
	}

	var outBuilder strings.Builder
	outBuilder.WriteString("// Code generated by gofront; DO NOT EDIT.\n")
	outBuilder.WriteString("package goxgen")
	outBuilder.WriteString("\n\nimport GoFront \"github.com/Alazar42/GoFront\"\n\n")

	// Write script block (if present) before the component function
	if blocks.Script != "" {
		outBuilder.WriteString(blocks.Script)
		outBuilder.WriteString("\n\n")
	}

	// Generate component function from template
	outBuilder.WriteString(fmt.Sprintf("func %s() GoFront.Component {\n", funcName))

	// Build component expression from tokens in template
	templateComponent := transpileTemplate(blocks.Template)
	outBuilder.WriteString("\treturn ")
	outBuilder.WriteString(templateComponent)
	outBuilder.WriteString("\n}")

	// Generate style file if styles are present
	if blocks.Style != "" {
		styleDir := filepath.Dir(srcPath)
		stylePath := filepath.Join(styleDir, name+".module.css")
		if err := os.WriteFile(stylePath, []byte(blocks.Style), 0o644); err != nil {
			return fmt.Errorf("write styles for %s: %w", name, err)
		}
	}

	// write file if changed
	existing, _ := os.ReadFile(genPath)
	if string(existing) != outBuilder.String() {
		if err := os.MkdirAll(filepath.Dir(genPath), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(genPath, []byte(outBuilder.String()), 0o644); err != nil {
			return err
		}
	}

	legacyPath := legacyGeneratedGoxPath(srcPath)
	if legacyPath != genPath {
		if _, err := os.Stat(legacyPath); err == nil {
			_ = os.Remove(legacyPath)
		}
	}
	return nil
}

type goxNode struct {
	tag      string
	text     string
	attrs    []string
	children []goxNode
	isText   bool
}

// transpileTemplate converts JSX-like template to GoFront component code.
func transpileTemplate(template string) string {
	tokens := tagRe.FindAllStringSubmatch(template, -1)
	index := 0

	var parse func(stopTag string) []goxNode
	parse = func(stopTag string) []goxNode {
		var nodes []goxNode
		for index < len(tokens) {
			tk := tokens[index]
			index++

			if tk[4] != "" {
				text := strings.TrimSpace(tk[4])
				if text != "" {
					nodes = append(nodes, goxNode{isText: true, text: strings.ReplaceAll(text, "\n", "\\n")})
				}
				continue
			}

			closing := tk[1] == "/"
			tag := tk[2]
			attrs := strings.TrimSpace(tk[3])

			if closing {
				if stopTag != "" && strings.EqualFold(tag, stopTag) {
					return nodes
				}
				continue
			}

			node := goxNode{tag: tag, attrs: parseGoxAttrs(attrs)}
			node.children = parse(tag)
			nodes = append(nodes, node)
		}
		return nodes
	}

	nodes := parse("")
	if len(nodes) == 0 {
		return "GoFront.Div()"
	}
	if len(nodes) == 1 {
		return renderGoxNode(nodes[0])
	}
	children := make([]string, 0, len(nodes))
	for _, node := range nodes {
		children = append(children, renderGoxNode(node))
	}
	return "GoFront.Div(" + strings.Join(children, ", ") + ")"
}

func parseGoxAttrs(attrs string) []string {
	if attrs == "" {
		return nil
	}
	var out []string
	for _, m := range attrRe.FindAllStringSubmatch(attrs, -1) {
		name := strings.ToLower(m[1])
		val := m[2]
		switch name {
		case "id":
			out = append(out, fmt.Sprintf("GoFront.ID(%q)", val))
		case "class":
			out = append(out, fmt.Sprintf("GoFront.Class(%q)", val))
		default:
			out = append(out, fmt.Sprintf("GoFront.Attr(%q, %q)", name, val))
		}
	}
	return out
}

func renderGoxNode(node goxNode) string {
	if node.isText {
		return fmt.Sprintf("GoFront.Text(%q)", node.text)
	}
	name := strings.Title(strings.ToLower(node.tag))
	if strings.EqualFold(name, "Text") {
		if len(node.children) == 0 {
			return "GoFront.Text(\"\")"
		}
		parts := make([]string, 0, len(node.children))
		for _, child := range node.children {
			if child.isText {
				parts = append(parts, child.text)
			} else {
				parts = append(parts, renderGoxNode(child))
			}
		}
		return fmt.Sprintf("GoFront.Text(%q)", strings.Join(parts, ""))
	}
	args := make([]string, 0, len(node.children))
	for _, child := range node.children {
		args = append(args, renderGoxNode(child))
	}
	expr := fmt.Sprintf("GoFront.%s()", name)
	if len(args) > 0 {
		expr = fmt.Sprintf("GoFront.%s(%s)", name, strings.Join(args, ", "))
	}
	if len(node.attrs) > 0 {
		expr += ".With(" + strings.Join(node.attrs, ", ") + ")"
	}
	return expr
}

func detectPackage(path string) string {
	dir := filepath.Dir(path)
	base := filepath.Base(dir)
	if base == "src" || base == "." {
		return "main"
	}
	return base
}
