package compiler

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// TranspileGoxFiles finds .gox files and generates corresponding _gox_gen.go files.
// Supports JSX-like tags with optional <script>, <style>, and <template> blocks (Svelte-like format).
func TranspileGoxFiles(srcDir string) error {
	return filepath.Walk(srcDir, func(path string, info os.FileInfo, err error) error {
		if err != nil || info == nil || info.IsDir() {
			return err
		}
		if strings.HasSuffix(path, ".gox") {
			// Generate .go file directly in src directory (not in subdirectory)
			// This ensures proper package detection and compilation
			genPath := strings.TrimSuffix(path, ".gox") + "_gox_gen.go"
			if err := transpileSingleGox(path, genPath); err != nil {
				return fmt.Errorf("transpile %s: %w", path, err)
			}
		}
		return nil
	})
}

var tagRe = regexp.MustCompile(`(?s)<(/?)([A-Za-z][A-Za-z0-9]*)\s*([^>]*)>|([^<]+)`)
var attrRe = regexp.MustCompile(`([a-zA-Z_:][-a-zA-Z0-9_:.]*)\s*=\s*"([^"]*)"`)

type GoxBlocks struct {
	Script   string
	Style    string
	Template string
}

// extractBlocks extracts <script>, <style>, and <template> blocks from .gox content
// Uses string manipulation instead of regex backreferences (not supported in Go regexp)
func extractBlocks(content string) GoxBlocks {
	blocks := GoxBlocks{}

	// Extract <script> block
	scriptStart := strings.Index(content, "<script")
	if scriptStart != -1 {
		scriptTagEnd := strings.Index(content[scriptStart:], ">")
		if scriptTagEnd != -1 {
			searchAfter := scriptStart + scriptTagEnd + 1
			scriptEnd := strings.Index(content[searchAfter:], "</script>")
			if scriptEnd != -1 {
				blocks.Script = strings.TrimSpace(content[searchAfter : searchAfter+scriptEnd])
			}
		}
	}

	// Extract <style> block
	styleStart := strings.Index(content, "<style")
	if styleStart != -1 {
		styleTagEnd := strings.Index(content[styleStart:], ">")
		if styleTagEnd != -1 {
			searchAfter := styleStart + styleTagEnd + 1
			styleEnd := strings.Index(content[searchAfter:], "</style>")
			if styleEnd != -1 {
				blocks.Style = strings.TrimSpace(content[searchAfter : searchAfter+styleEnd])
			}
		}
	}

	// Extract <template> block
	templateStart := strings.Index(content, "<template")
	if templateStart != -1 {
		templateTagEnd := strings.Index(content[templateStart:], ">")
		if templateTagEnd != -1 {
			searchAfter := templateStart + templateTagEnd + 1
			templateEnd := strings.Index(content[searchAfter:], "</template>")
			if templateEnd != -1 {
				blocks.Template = strings.TrimSpace(content[searchAfter : searchAfter+templateEnd])
			}
		}
	}

	// If no <template> block found, use content minus the extracted blocks
	if blocks.Template == "" {
		templateContent := content

		// Remove script block if present
		if scriptStart != -1 {
			scriptTagEnd := strings.Index(content[scriptStart:], ">")
			if scriptTagEnd != -1 {
				searchAfter := scriptStart + scriptTagEnd + 1
				scriptEnd := strings.Index(content[searchAfter:], "</script>")
				if scriptEnd != -1 {
					scriptFullEnd := searchAfter + scriptEnd + len("</script>")
					templateContent = templateContent[:scriptStart] + templateContent[scriptFullEnd:]
				}
			}
		}

		// Remove style block if present
		if styleStart != -1 {
			styleTagEnd := strings.Index(content[styleStart:], ">")
			if styleTagEnd != -1 {
				searchAfter := styleStart + styleTagEnd + 1
				styleEnd := strings.Index(content[searchAfter:], "</style>")
				if styleEnd != -1 {
					styleFullEnd := searchAfter + styleEnd + len("</style>")
					templateContent = templateContent[:styleStart] + templateContent[styleFullEnd:]
				}
			}
		}

		blocks.Template = strings.TrimSpace(templateContent)
	}

	return blocks
}

func transpileSingleGox(srcPath, genPath string) error {
	f, err := os.Open(srcPath)
	if err != nil {
		return err
	}
	defer f.Close()
	content, err := io.ReadAll(f)
	if err != nil {
		return err
	}

	blocks := extractBlocks(string(content))

	// Get component name and package
	base := filepath.Base(srcPath)
	name := strings.TrimSuffix(base, filepath.Ext(base))
	funcName := strings.Title(name)
	// if in components or pages folder, keep conventional suffixes
	// pages/home.gox -> HomePage
	if strings.Contains(srcPath, string(filepath.Separator)+"pages") {
		funcName = strings.Title(name) + "Page"
	}

	var outBuilder strings.Builder
	outBuilder.WriteString("// Code generated by gofront; DO NOT EDIT.\n")
	outBuilder.WriteString("package ")
	outBuilder.WriteString(detectPackage(srcPath))
	outBuilder.WriteString("\n\nimport GoFront \"github.com/Alazar42/GoFront\"\n\n")

	// Write script block (if present) before the component function
	if blocks.Script != "" {
		outBuilder.WriteString(blocks.Script)
		outBuilder.WriteString("\n\n")
	}

	// Generate component function from template
	outBuilder.WriteString(fmt.Sprintf("func %s() GoFront.Component {\n", funcName))

	// Build component expression from tokens in template
	templateComponent := transpileTemplate(blocks.Template)
	outBuilder.WriteString("\treturn ")
	outBuilder.WriteString(templateComponent)
	outBuilder.WriteString("\n}")

	// Generate style file if styles are present
	if blocks.Style != "" {
		styleDir := filepath.Dir(srcPath)
		stylePath := filepath.Join(styleDir, name+".module.css")
		if err := os.WriteFile(stylePath, []byte(blocks.Style), 0o644); err != nil {
			return fmt.Errorf("write styles for %s: %w", name, err)
		}
	}

	// write file if changed
	existing, _ := os.ReadFile(genPath)
	if string(existing) != outBuilder.String() {
		if err := os.WriteFile(genPath, []byte(outBuilder.String()), 0o644); err != nil {
			return err
		}
	}
	return nil
}

// transpileTemplate converts JSX-like template to GoFront component code
func transpileTemplate(template string) string {
	tokens := tagRe.FindAllStringSubmatch(template, -1)
	var exprStack []string
	var stack []string

	emitOpen := func(tag string, attrs string) string {
		tagName := strings.Title(strings.ToLower(tag))
		var call string
		switch tagName {
		case "Text":
			call = "GoFront.Text(\"\")"
		default:
			call = fmt.Sprintf("GoFront.%s(", tagName)
		}
		attrsCalls := []string{}
		if attrs != "" {
			for _, m := range attrRe.FindAllStringSubmatch(attrs, -1) {
				name := strings.ToLower(m[1])
				val := m[2]
				if name == "id" {
					attrsCalls = append(attrsCalls, fmt.Sprintf("GoFront.ID(%q)", val))
				} else if name == "class" {
					attrsCalls = append(attrsCalls, fmt.Sprintf("GoFront.Class(%q)", val))
				}
			}
		}
		if len(attrsCalls) > 0 {
			return "OPEN::" + (call + ")" + ".With(" + strings.Join(attrsCalls, ", ") + ")")
		}
		return "OPEN::" + call
	}

	for _, tk := range tokens {
		if tk[4] != "" {
			// text node
			txt := strings.TrimSpace(tk[4])
			if txt != "" {
				txt = strings.ReplaceAll(txt, "\n", "\\n")
				exprStack = append(exprStack, fmt.Sprintf("GoFront.Text(%q)", txt))
			}
			continue
		}
		closing := tk[1] == "/"
		tag := tk[2]
		attrs := strings.TrimSpace(tk[3])
		if !closing {
			tagExpr := emitOpen(tag, attrs)
			exprStack = append(exprStack, tagExpr)
			stack = append(stack, "(")
		} else {
			var children []string
			for len(exprStack) > 0 {
				last := exprStack[len(exprStack)-1]
				exprStack = exprStack[:len(exprStack)-1]
				if strings.HasPrefix(last, "GoFront.") {
					for i := len(children)/2 - 1; i >= 0; i-- {
						opp := len(children) - 1 - i
						children[i], children[opp] = children[opp], children[i]
					}
					var b strings.Builder
					if strings.HasSuffix(last, ")") && strings.Contains(last, ".With(") {
						idx := strings.Index(last, ")")
						baseCall := last[:idx+1]
						withPart := last[idx+1:]
						b.WriteString(baseCall)
						if len(children) > 0 {
							b.WriteString(strings.Join(children, ", "))
						}
						b.WriteString(withPart)
					} else {
						if strings.HasSuffix(last, "(") {
							b.WriteString(last)
						} else if strings.HasSuffix(last, ")") {
							b.WriteString(last)
							b.WriteString("(")
						} else {
							b.WriteString(last + "(")
						}
						if len(children) > 0 {
							b.WriteString(strings.Join(children, ", "))
						}
						b.WriteString(")")
					}
					exprStack = append(exprStack, b.String())
					break
				}
				children = append(children, last)
			}
		}
	}

	finalExpr := "GoFront.Div()"
	if len(exprStack) > 0 {
		finalExpr = exprStack[len(exprStack)-1]
	}
	return finalExpr
}

func detectPackage(path string) string {
	dir := filepath.Dir(path)
	base := filepath.Base(dir)
	if base == "src" || base == "." {
		return "main"
	}
	return base
}
